/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.klerkframework.klerk


import dev.klerkframework.klerk.command.Command
import dev.klerkframework.klerk.command.CommandToken
import dev.klerkframework.klerk.command.ProcessingOptions
import dev.klerkframework.klerk.storage.RamStorage
import kotlinx.coroutines.runBlocking
import mu.KotlinLogging
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail


class BlockTriggeringInstanceNonInstanceEventBlockTest {

    private val logger = KotlinLogging.logger {}

    @Test
    fun read() {

        runBlocking {
            val bc = BookViews()
            val collections = Views(bc, AuthorViews(bc.all))
            val klerk = createKlerk(collections, RamStorage())
            klerk.meta.start()

            val rowlingId = createAuthorJKRowling(klerk)

            val result = klerk.handle(
                Command(ImproveAuthor, rowlingId, null),
                Ctx.system(),
            ).getOrElse { fail() }

            assertTrue(result.transitionedModels.contains(rowlingId))

            val model = klerk.read(Ctx.system()) { get(rowlingId) }

            assertEquals(AuthorStates.Established.name, model.state)
        }
    }
}
